playground/build.gradle
playground/src/main/AndroidManifest.xml
playground/src/main/java/org/navgurukul/playground/di/PlaygroundModules.kt
playground/src/main/java/org/navgurukul/playground/repo/PlaygroundRepository.kt
playground/src/main/java/org/navgurukul/playground/repo/PlaygroundRepositoryImpl.kt
playground/src/main/java/org/navgurukul/playground/ui/PlaygroundActivity.kt
playground/src/main/java/org/navgurukul/playground/ui/PlaygroundViewModel.kt
playground/src/main/res/drawable/bg_error.xml
playground/src/main/res/drawable/bg_input.xml
playground/src/main/res/drawable/bg_peek_layout.xml
playground/src/main/res/drawable/ic_clear.xml
playground/src/main/res/drawable/ic_enter_round.xml
playground/src/main/res/layout/activity_playground.xml
playground/src/main/res/layout/bottom_sheet_output.xml
playground/src/main/res/menu/playground_menu.xml
playground/src/main/res/values/dimens.xml
playground/src/main/res/values/strings.xml

- Cache code written in shared prefs
- UI improvements
Closes #38, #39. #40

Playground UI improvements and fixes

---

app/build.gradle
app/src/main/java/org/merakilearn/di/Modules.kt
learn/src/main/java/org/navgurukul/learn/di/LearnModules.kt

This PR introduces necessary changes to fetch server url from BuildConfig which is injected based on the build type (debug, release). Also moved di for retrofit to app module as the url is configured in app module

Server URL from BuildConfig

---

app/src/main/java/org/merakilearn/MainActivity.kt

fixed crash #54

---

chat/src/main/java/org/navgurukul/chat/core/utils/ExternalApplicationsUtil.kt
chat/src/main/java/org/navgurukul/chat/features/home/room/detail/RoomDetailFragment.kt
chat/src/main/res/values/strings.xml

clickable links in chat

---

app/src/main/java/org/merakilearn/ProfileActivity.kt
app/src/main/java/org/merakilearn/datasource/ApplicationRepo.kt
app/src/main/java/org/merakilearn/datasource/network/model/LoginResponse.kt
app/src/main/java/org/merakilearn/ui/onboarding/LoginFragment.kt
app/src/main/java/org/merakilearn/ui/onboarding/WelcomeViewModel.kt

New users will go through bot flow now regardless of the login medium

Fix new user login flow

---

learn/src/main/java/org/navgurukul/learn/util/LearnUtils.kt

Removed non-null asserted (!!)

removed force not null

---

app/src/main/java/org/merakilearn/MainActivity.kt
app/src/main/java/org/merakilearn/ProfileActivity.kt
app/src/main/java/org/merakilearn/util/AppUtils.kt

null check for user login response

---

app/src/main/java/org/merakilearn/MainActivity.kt
app/src/main/java/org/merakilearn/datasource/ApplicationRepo.kt
app/src/main/java/org/merakilearn/util/AppUtils.kt

1. Saved login response after matrix sdk login
2. Clear login shared pref if user response is null
3. Removed run block

saving response after matrix login

---

app/src/main/java/org/merakilearn/MainActivity.kt
app/src/main/java/org/merakilearn/fcm/MerakiMessagingService.kt

- also fixed wrong use of elvis operator

Image Loading in notification moved to background thread

---

app/build.gradle
app/src/main/java/org/merakilearn/ui/discover/DiscoverViewModel.kt
app/src/main/java/org/merakilearn/util/DateTimeUtil.kt

Replaced LocalDateTime dependency with alternatives
fixed date crash on hindi specific dates

fixed chaquopy crash

---

typing/build.gradle
typing/src/main/java/org/navgurukul/typingguru/ui/WebViewActivity.kt
typing/src/main/java/org/navgurukul/typingguru/utils/RemoteConfig.kt
typing/src/main/java/org/navgurukul/typingguru/utils/TypingGuruPreferenceManager.java
typing/src/main/res/xml/remote_config_defaults.xml

remote config added

---

app/src/main/java/org/merakilearn/EnrollActivity.kt
app/src/main/java/org/merakilearn/EnrollViewModel.kt
app/src/main/java/org/merakilearn/datasource/network/model/Classes.kt
app/src/main/res/layout/activity_discover_enroll.xml
app/src/main/res/values/strings.xml

https://www.notion.so/meraki/151fbd4c4b3249088849f75b4d720eab?v=ed751ccb66e149148341dbb889c3a09d&p=9ba00fd37b3e4c58876344b2d8e90f75

Added an option to join class in the Class details screen

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/merakilearn/datasource/Config.kt
app/src/main/java/org/merakilearn/datasource/SettingsRepo.kt
app/src/main/java/org/merakilearn/di/Modules.kt
app/src/main/java/org/merakilearn/ui/profile/ProfileActivity.kt
app/src/main/java/org/merakilearn/ui/profile/ProfileViewModel.kt
app/src/main/res/layout/activity_profile.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/remote_config_defaults.xml
buildSrc/src/main/kotlin/Dependencies.kt
core/build.gradle.kts
core/src/main/java/org/merakilearn/core/navigator/MerakiNavigator.kt

Added an option to update server url
Privacy policy delegated to view model
Privacy policy opened using chrome tabs

Server url and privacy policy in profile

---

app/build.gradle.kts
app/src/main/java/org/merakilearn/datasource/ApplicationRepo.kt
app/src/main/java/org/merakilearn/datasource/Config.kt
app/src/main/java/org/merakilearn/datasource/network/model/Classes.kt
app/src/main/java/org/merakilearn/datasource/network/model/ClassesContainer.kt
app/src/main/java/org/merakilearn/datasource/network/model/Language.kt
app/src/main/java/org/merakilearn/datasource/network/model/LoginRequest.kt
app/src/main/java/org/merakilearn/datasource/network/model/LoginResponse.kt
app/src/main/java/org/merakilearn/datasource/network/model/UserUpdate.kt
app/src/main/java/org/merakilearn/datasource/network/model/UserUpdateContainer.kt
app/src/main/java/org/merakilearn/di/Modules.kt
app/src/main/java/org/merakilearn/ui/home/HomeViewModel.kt
app/src/main/java/org/merakilearn/ui/onboarding/WelcomeViewModel.kt
buildSrc/src/main/kotlin/Dependencies.kt
core/build.gradle.kts
core/src/main/java/org/merakilearn/core/extentions/StringExntensions.kt
learn/build.gradle.kts
learn/src/main/java/org/navgurukul/learn/courses/db/models/Course.kt
learn/src/main/java/org/navgurukul/learn/courses/db/models/Exercise.kt
learn/src/main/java/org/navgurukul/learn/courses/db/models/ExerciseSlugDetail.kt
learn/src/main/java/org/navgurukul/learn/courses/db/models/Pathway.kt
learn/src/main/java/org/navgurukul/learn/courses/db/typeadapters/Converter.kt
learn/src/main/java/org/navgurukul/learn/courses/network/model/CourseExerciseContainer.kt
learn/src/main/java/org/navgurukul/learn/courses/network/model/PathwayContainer.kt
learn/src/main/java/org/navgurukul/learn/courses/network/model/PathwayCourseContainer.kt
learn/src/main/java/org/navgurukul/learn/di/LearnModules.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/CourseSlugDetailActivity.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/adapter/ExerciseSlugAdapter.kt

Moshi offers much more than gson which is unmaintained and doesn't utilise full power of kotlin. Moreover Moshi is used internally inside matrix so we were using two libraries to parse json. This PR removes gson from the app and migrated the code usages to Moshi

Migrated from gson to moshi

---

python/src/main/java/org/navgurukul/playground/repo/PythonRepositoryImpl.kt

Issue reported by Apoorva Chaudhari.

Python playground bug resolved

---

learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseFragment.kt

Workaround for html to plain text convertor, Dhanshri will replace the patch with the stable solution.

indent issue solved, reported by dhanshri

---

learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseActivity.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseActivityViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseFragment.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseFragmentViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/adapter/DotItemDecoration.kt
learn/src/main/res/drawable/ic_type_text_complete.xml
learn/src/main/res/drawable/ic_type_text_selected.xml
learn/src/main/res/drawable/light_gradient_toolbar_background.xml
learn/src/main/res/layout/fragment_exercise.xml
learn/src/main/res/layout/item_course.xml
learn/src/main/res/values/colors.xml

Removing mark as a complete button and some color changes in UI

Dhan UI changes

---

learn/src/main/java/org/navgurukul/learn/courses/db/CoursesDatabase.kt
learn/src/main/java/org/navgurukul/learn/courses/db/models/Course.kt
learn/src/main/java/org/navgurukul/learn/courses/network/SaralCoursesApi.kt
learn/src/main/java/org/navgurukul/learn/courses/network/model/LearningTrackStatus.kt
learn/src/main/java/org/navgurukul/learn/courses/repository/LearnRepo.kt
learn/src/main/java/org/navgurukul/learn/di/LearnModules.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/CourseContentActivityViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/LearnFragment.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/adapter/CourseAdapter.kt
learn/src/main/res/layout/batches_in_exercise.xml
learn/src/main/res/layout/item_batch_exercise.xml
learn/src/main/res/layout/item_course.xml
learn/src/main/res/values/colors.xml

Progress tracking in percentage feature using completed portion

Dhan progress tracker

---

python/src/main/java/org/navgurukul/playground/editor/PythonEditorFragment.kt
python/src/main/java/org/navgurukul/playground/editor/PythonEditorViewModel.kt

Apply method was used for setters.
Reformatted code to ensure readability.

Anurag issues

---

app/src/main/java/org/merakilearn/InstallReferrerManager.kt
app/src/main/java/org/merakilearn/datasource/UserRepo.kt
app/src/main/java/org/merakilearn/datasource/network/SaralApi.kt
app/src/main/java/org/merakilearn/datasource/network/UserUpdateName.kt
app/src/main/java/org/merakilearn/datasource/network/model/UserUpdate.kt
app/src/main/java/org/merakilearn/datasource/network/model/UserUpdateNameSafe.kt
app/src/main/java/org/merakilearn/ui/ScratchActivity.kt
app/src/main/java/org/merakilearn/ui/onboarding/SelectCourseFragment.kt
app/src/main/java/org/merakilearn/ui/playground/PlaygroundFragment.kt
buildSrc/src/main/kotlin/Dependencies.kt
core/src/main/res/xml/remote_config_defaults.xml
learn/src/main/java/org/navgurukul/learn/courses/network/model/ConstantString.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/ExerciseFragment.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/viewholder/CodeCourseViewHolder.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/viewholder/QuestionCodeCourseViewHolder.kt

Merging some resolved bug 
1. Share as url
2. Remove scratch pathway
3. Added scratch existing warning
4. Added delete file warning
5. Name issue in the profile
6. Syntax issue in code

Shaina/main release 1.5.50

---

app/src/main/java/org/merakilearn/ui/playground/PlaygroundFragment.kt

Security Exception Fixed

---

app/src/main/java/org/merakilearn/ui/onboarding/OnBoardingViewModel.kt
app/src/main/java/org/merakilearn/ui/playground/PlaygroundViewModel.kt
learn/src/main/java/org/navgurukul/learn/courses/network/SaralCoursesApi.kt
learn/src/main/java/org/navgurukul/learn/courses/repository/LearnRepo.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/ClassFragmentViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/CourseContentActivityViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/LearnFragmentViewModel.kt
learn/src/main/java/org/navgurukul/learn/ui/learn/viewholder/AssessmentFragmentViewModel.kt

Replacing the new API for posting the complete exercised

replacing the learningTrackStatus api to exerciseIdComplete
